name: Playwright Test Suite (POS | NEG | UI)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  pos-tests:
    name: Positive Test Cases
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Positive Tests
        run: npx playwright test tests/pos-test.spec.js

      - name: Upload POS report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pos-test-report
          path: playwright-report/


  neg-tests:
    name: Negative Test Cases
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Negative Tests
        run: npx playwright test tests/neg-test.spec.js

      - name: Upload NEG report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: neg-test-report
          path: playwright-report/


  ui-tests:
    name: UI Test Cases
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run UI Tests
        run: npx playwright test tests/ui-test.spec.js

      - name: Upload UI report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-report
          path: playwright-report/
